// Copyright Dave Abrahams 2013. Distributed under the Boost
// Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#ifndef CONFIG_DWA2013110_H
# define CONFIG_DWA2013110_H

// subconvert was originally written with autoconf.  To avoid
// modifying that code at all, we supply this header which is normally
// generated by the autoconf process.  If we replace subconvert's
// autoconf with a first class CMakeLists.txt, this file can go away.

#endif // CONFIG_DWA2013110_H
