// Copyright Dave Abrahams 2013. Distributed under the Boost
// Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#ifndef SYSTEM_DWA2013110_HPP
# define SYSTEM_DWA2013110_HPP

// subconvert was originally written with autoconf.  To avoid
// modifying that code at all, we supply this header which is normally
// generated by the autoconf process from its system.hpp.in.  If we
// replace subconvert's autoconf with a first class CMakeLists.txt,
// we'd rename its system.hpp.in to system.hpp, overwriting this file.

# include "subconvert/src/system.hpp.in"

#endif // SYSTEM_DWA2013110_HPP
